// AUTO-GENERATED by scripts/gen-cidg-voices.mjs — DO NOT EDIT BY HAND.
// Re-run: node scripts/gen-cidg-voices.mjs

// Voice-of-the-Buyer reddit market-research subset that motivates CIDG. Numeric
// series (keyword/tool counts, monthly tier activity, subreddit/score stats) are
// MEASURED from rl-env/research/eda artifacts. The post leaderboard + buyer
// quotes are a CURATED, on-topic subset (the incident/reliability posts) with
// real subreddit + score + permalink preserved.

export type PainKeyword = { term: string; count: number };
export type ToolMention = { tool: string; count: number; category: string; note: string | null };
export type SubredditCount = { name: string; posts: number };
export type TierSeries = { tier: string; points: number[] };
export type VoicePost = { id: string; subreddit: string; score: number; comments: number; title: string; url: string; theme: string };
export type BuyerQuote = { subreddit: string; score: number; keyword: string; postTitle: string; body: string; url: string };

export const VOICES_STATS = {
	"totalPosts": 809,
	"totalComments": 2970,
	"subredditCount": 10,
	"earliest": "2013-06-14",
	"latest": "2025-05-16",
	"scoreMean": 1926.5,
	"scoreMedian": 436,
	"scoreMax": 44750
} as const;

export const PAIN_KEYWORDS: PainKeyword[] = [
	{
		"term": "trust",
		"count": 74
	},
	{
		"term": "outage",
		"count": 48
	},
	{
		"term": "toil",
		"count": 20
	},
	{
		"term": "root cause",
		"count": 18
	},
	{
		"term": "rca",
		"count": 11
	},
	{
		"term": "postmortem",
		"count": 11
	},
	{
		"term": "rollback",
		"count": 10
	},
	{
		"term": "post-mortem",
		"count": 8
	},
	{
		"term": "false positive",
		"count": 7
	},
	{
		"term": "p1",
		"count": 5
	},
	{
		"term": "downtime",
		"count": 4
	},
	{
		"term": "blameless",
		"count": 4
	},
	{
		"term": "p0",
		"count": 2
	},
	{
		"term": "blast radius",
		"count": 1
	},
	{
		"term": "3am",
		"count": 1
	},
	{
		"term": "sev1",
		"count": 1
	},
	{
		"term": "out of hours",
		"count": 1
	},
	{
		"term": "mttr",
		"count": 1
	},
	{
		"term": "trustworthy",
		"count": 1
	}
];

export const TOOL_MENTIONS: ToolMention[] = [
	{
		"tool": "terraform",
		"count": 92,
		"category": "iac",
		"note": "IaC incumbent"
	},
	{
		"tool": "kubernetes",
		"count": 77,
		"category": "orchestration",
		"note": "orchestration won; debate moved to how"
	},
	{
		"tool": "docker",
		"count": 72,
		"category": "orchestration",
		"note": "containerization assumed"
	},
	{
		"tool": "pulumi",
		"count": 47,
		"category": "iac",
		"note": "51% of Terraform — live challenger, not noise"
	},
	{
		"tool": "helm",
		"count": 44,
		"category": "orchestration",
		"note": null
	},
	{
		"tool": "gitlab",
		"count": 37,
		"category": "ci/cd",
		"note": "54% above Jenkins — greenfield momentum"
	},
	{
		"tool": "highlight",
		"count": 35,
		"category": "observability",
		"note": null
	},
	{
		"tool": "ansible",
		"count": 29,
		"category": "iac",
		"note": null
	},
	{
		"tool": "k8s",
		"count": 29,
		"category": "orchestration",
		"note": null
	},
	{
		"tool": "datadog",
		"count": 26,
		"category": "observability",
		"note": "commercial observability leader"
	},
	{
		"tool": "jenkins",
		"count": 24,
		"category": "ci/cd",
		"note": "mentions skew 'migrate away'"
	},
	{
		"tool": "rootly",
		"count": 15,
		"category": "incident",
		"note": "emerging incident-mgmt vendor signal"
	},
	{
		"tool": "argo",
		"count": 14,
		"category": "orchestration",
		"note": null
	},
	{
		"tool": "prometheus",
		"count": 13,
		"category": "observability",
		"note": null
	},
	{
		"tool": "tempo",
		"count": 12,
		"category": "observability",
		"note": null
	},
	{
		"tool": "elastic",
		"count": 11,
		"category": "observability",
		"note": null
	},
	{
		"tool": "github actions",
		"count": 10,
		"category": "ci/cd",
		"note": null
	},
	{
		"tool": "puppet",
		"count": 10,
		"category": "iac",
		"note": null
	},
	{
		"tool": "splunk",
		"count": 10,
		"category": "observability",
		"note": null
	},
	{
		"tool": "chef",
		"count": 7,
		"category": "iac",
		"note": null
	},
	{
		"tool": "pagerduty",
		"count": 7,
		"category": "incident",
		"note": "surprisingly low for the on-call incumbent"
	},
	{
		"tool": "grafana",
		"count": 7,
		"category": "observability",
		"note": null
	},
	{
		"tool": "openai",
		"count": 6,
		"category": "ai",
		"note": null
	},
	{
		"tool": "sentry",
		"count": 5,
		"category": "observability",
		"note": null
	},
	{
		"tool": "cursor",
		"count": 4,
		"category": "ai",
		"note": null
	},
	{
		"tool": "dynatrace",
		"count": 4,
		"category": "observability",
		"note": null
	},
	{
		"tool": "litmus",
		"count": 3,
		"category": "incident",
		"note": null
	},
	{
		"tool": "copilot",
		"count": 3,
		"category": "ai",
		"note": null
	},
	{
		"tool": "claude",
		"count": 3,
		"category": "ai",
		"note": null
	},
	{
		"tool": "argocd",
		"count": 3,
		"category": "orchestration",
		"note": null
	},
	{
		"tool": "flux",
		"count": 3,
		"category": "orchestration",
		"note": null
	},
	{
		"tool": "cloudwatch",
		"count": 2,
		"category": "observability",
		"note": null
	},
	{
		"tool": "gpt-4",
		"count": 2,
		"category": "ai",
		"note": null
	},
	{
		"tool": "gpt-4o",
		"count": 2,
		"category": "ai",
		"note": null
	},
	{
		"tool": "istio",
		"count": 2,
		"category": "orchestration",
		"note": null
	},
	{
		"tool": "newrelic",
		"count": 2,
		"category": "observability",
		"note": null
	},
	{
		"tool": "loki",
		"count": 2,
		"category": "observability",
		"note": null
	},
	{
		"tool": "devin",
		"count": 2,
		"category": "ai",
		"note": null
	},
	{
		"tool": "azure monitor",
		"count": 1,
		"category": "observability",
		"note": null
	},
	{
		"tool": "circleci",
		"count": 1,
		"category": "ci/cd",
		"note": null
	},
	{
		"tool": "victoriametrics",
		"count": 1,
		"category": "observability",
		"note": null
	},
	{
		"tool": "spinnaker",
		"count": 1,
		"category": "ci/cd",
		"note": null
	},
	{
		"tool": "containerd",
		"count": 1,
		"category": "other",
		"note": null
	},
	{
		"tool": "podman",
		"count": 1,
		"category": "other",
		"note": null
	},
	{
		"tool": "victorops",
		"count": 1,
		"category": "incident",
		"note": null
	},
	{
		"tool": "kibana",
		"count": 1,
		"category": "observability",
		"note": null
	},
	{
		"tool": "fluentd",
		"count": 1,
		"category": "observability",
		"note": null
	},
	{
		"tool": "signoz",
		"count": 1,
		"category": "observability",
		"note": null
	}
];

export const SUBREDDITS: SubredditCount[] = [
	{
		"name": "Entrepreneur",
		"posts": 100
	},
	{
		"name": "ExperiencedDevs",
		"posts": 100
	},
	{
		"name": "aws",
		"posts": 100
	},
	{
		"name": "azure",
		"posts": 100
	},
	{
		"name": "devops",
		"posts": 100
	},
	{
		"name": "programming",
		"posts": 100
	},
	{
		"name": "sre",
		"posts": 100
	},
	{
		"name": "startups",
		"posts": 100
	},
	{
		"name": "chaosengineering",
		"posts": 7
	},
	{
		"name": "gcp",
		"posts": 2
	}
];

// Shared month axis (YYYY-MM) for the tier activity series below.
export const ACTIVITY_MONTHS: string[] = ["2013-06","2013-08","2014-03","2014-09","2015-03","2015-04","2015-06","2015-09","2015-12","2016-02","2016-04","2016-05","2016-08","2016-10","2016-11","2016-12","2017-01","2017-02","2017-03","2017-04","2017-05","2017-06","2017-07","2017-08","2017-09","2017-10","2017-11","2017-12","2018-01","2018-02","2018-03","2018-04","2018-05","2018-06","2018-07","2018-08","2018-09","2018-10","2018-11","2018-12","2019-01","2019-02","2019-03","2019-04","2019-05","2019-06","2019-07","2019-08","2019-09","2019-10","2019-11","2019-12","2020-01","2020-02","2020-03","2020-04","2020-05","2020-06","2020-07","2020-08","2020-09","2020-10","2020-11","2020-12","2021-01","2021-02","2021-03","2021-04","2021-05","2021-06","2021-07","2021-08","2021-09","2021-10","2021-11","2021-12","2022-01","2022-02","2022-03","2022-04","2022-05","2022-06","2022-07","2022-08","2022-09","2022-10","2022-11","2022-12","2023-01","2023-02","2023-03","2023-04","2023-05","2023-06","2023-07","2023-08","2023-11","2024-01","2024-02","2024-06","2024-07","2024-08","2024-09","2024-10","2024-11","2024-12","2025-01","2025-02","2025-03","2025-04","2025-05"];

export const TIER_SERIES: TierSeries[] = [
	{
		"tier": "startup",
		"points": [
			1,
			2,
			1,
			1,
			1,
			1,
			1,
			2,
			0,
			2,
			2,
			0,
			1,
			1,
			2,
			1,
			4,
			1,
			3,
			0,
			3,
			1,
			3,
			2,
			1,
			2,
			4,
			1,
			2,
			2,
			1,
			4,
			1,
			1,
			2,
			0,
			0,
			4,
			0,
			3,
			3,
			1,
			2,
			1,
			0,
			0,
			0,
			0,
			1,
			0,
			1,
			1,
			3,
			1,
			4,
			3,
			7,
			5,
			5,
			5,
			1,
			1,
			6,
			2,
			3,
			8,
			3,
			3,
			4,
			0,
			3,
			5,
			2,
			1,
			5,
			4,
			1,
			2,
			1,
			2,
			0,
			0,
			2,
			2,
			4,
			2,
			2,
			2,
			2,
			0,
			3,
			2,
			0,
			0,
			1,
			1,
			1,
			0,
			1,
			1,
			1,
			0,
			3,
			2,
			1,
			2,
			0,
			1,
			0,
			0,
			0
		]
	},
	{
		"tier": "sre",
		"points": [
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			1,
			1,
			0,
			0,
			1,
			0,
			0,
			0,
			0,
			1,
			0,
			2,
			1,
			1,
			4,
			2,
			1,
			3,
			2,
			2,
			3,
			2,
			1,
			2,
			2,
			4,
			4,
			2,
			1,
			0,
			2,
			1,
			0,
			4,
			3,
			1,
			1,
			2,
			3,
			3,
			4,
			2,
			2,
			1,
			4,
			0,
			0,
			4,
			1,
			1,
			1,
			2,
			6,
			0,
			8,
			0,
			3,
			5,
			7,
			4,
			8,
			7,
			11,
			13,
			9,
			4,
			7,
			8,
			8,
			7,
			14,
			7,
			9,
			3,
			8,
			8,
			8,
			7,
			5,
			6,
			6,
			7,
			10,
			12,
			10,
			9,
			10,
			3,
			2,
			0,
			0,
			2,
			1,
			6,
			5,
			17,
			6,
			2,
			2,
			6,
			3,
			4,
			4,
			5
		]
	},
	{
		"tier": "sre-cloud",
		"points": [
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			1,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			1,
			0,
			0,
			0,
			1,
			0,
			0,
			0,
			0,
			0,
			1,
			1,
			0,
			0,
			1,
			0,
			1,
			2,
			0,
			0,
			1,
			2,
			3,
			3,
			1,
			5,
			1,
			0,
			6,
			2,
			7,
			4,
			2,
			3,
			7,
			2,
			4,
			7,
			5,
			9,
			6,
			4,
			5,
			3,
			4,
			2,
			3,
			3,
			6,
			9,
			5,
			2,
			1,
			3,
			1,
			1,
			0,
			1,
			2,
			5,
			4,
			4,
			8,
			5,
			3,
			3,
			1,
			5,
			4,
			0,
			0,
			1,
			0,
			1,
			1,
			1,
			5,
			0,
			1,
			0,
			1,
			2,
			0,
			2,
			1
		]
	}
];

export const TOP_POSTS: VoicePost[] = [
	{
		"id": "uqrwq2",
		"subreddit": "devops",
		"score": 351,
		"comments": 108,
		"title": "How we deploy to production over 100 times a day",
		"url": "https://reddit.com/r/devops/comments/uqrwq2/how_we_deploy_to_production_over_100_times_a_day/",
		"theme": "deploy safety"
	},
	{
		"id": "1kk685o",
		"subreddit": "devops",
		"score": 349,
		"comments": 166,
		"title": "I'm done applying. I'll fix your cloud/SRE problem in 48 hours and for free.",
		"url": "https://reddit.com/r/devops/comments/1kk685o/im_done_applying_ill_fix_your_cloudsre_problem_in/",
		"theme": "production fires"
	},
	{
		"id": "1axfxob",
		"subreddit": "devops",
		"score": 340,
		"comments": 154,
		"title": "The next time your devs complain about production being locked down:",
		"url": "https://reddit.com/r/devops/comments/1axfxob/the_next_time_your_devs_complain_about_production/",
		"theme": "prod safety"
	},
	{
		"id": "1i538r1",
		"subreddit": "devops",
		"score": 324,
		"comments": 184,
		"title": "Why is DevOps still such a fragmented, exhausting (and ofc costly) mess in 2025?",
		"url": "https://reddit.com/r/devops/comments/1i538r1/why_is_devops_still_such_a_fragmented_exhausting/",
		"theme": "tool sprawl"
	},
	{
		"id": "rh1rw7",
		"subreddit": "aws",
		"score": 270,
		"comments": 110,
		"title": "Another AWS outage?",
		"url": "https://reddit.com/r/aws/comments/rh1rw7/another_aws_outage/",
		"theme": "cloud outage"
	},
	{
		"id": "1e6zlq6",
		"subreddit": "azure",
		"score": 145,
		"comments": 86,
		"title": "Microsoft and Crowdstrike Outage",
		"url": "https://reddit.com/r/AZURE/comments/1e6zlq6/microsoft_and_crowdstrike_outage/",
		"theme": "cloud outage"
	},
	{
		"id": "xi9fku",
		"subreddit": "sre",
		"score": 90,
		"comments": 25,
		"title": "A \"real\" day in the life of an SRE",
		"url": "https://reddit.com/r/sre/comments/xi9fku/a_real_day_in_the_life_of_an_sre_we_have_all_seen/",
		"theme": "toil"
	},
	{
		"id": "1foghyl",
		"subreddit": "sre",
		"score": 66,
		"comments": 29,
		"title": "Have you ever caused a major outage?",
		"url": "https://reddit.com/r/sre/comments/1foghyl/have_you_ever_caused_a_major_outage/",
		"theme": "outage / RCA"
	},
	{
		"id": "113t8ou",
		"subreddit": "sre",
		"score": 66,
		"comments": 56,
		"title": "Became SRE. Highly regret it. Help.",
		"url": "https://reddit.com/r/sre/comments/113t8ou/became_sre_highly_regret_it_help/",
		"theme": "on-call fatigue"
	},
	{
		"id": "1e0t000",
		"subreddit": "sre",
		"score": 63,
		"comments": 66,
		"title": "i once got paged on the subway and emerged in the midst of a SEV0 outage",
		"url": "https://reddit.com/r/sre/comments/1e0t000/i_once_got_paged_on_the_subway_underground_and/",
		"theme": "on-call fatigue"
	},
	{
		"id": "1fz23bq",
		"subreddit": "sre",
		"score": 62,
		"comments": 4,
		"title": "seeing my name in the postmortem",
		"url": "https://reddit.com/r/sre/comments/1fz23bq/seeing_my_name_in_the_postmortem/",
		"theme": "postmortem"
	},
	{
		"id": "wk443h",
		"subreddit": "sre",
		"score": 56,
		"comments": 6,
		"title": "Don't do this with your k8s health checks",
		"url": "https://reddit.com/r/sre/comments/wk443h/dont_do_this_with_your_k8s_health_checks/",
		"theme": "outage / fix"
	},
	{
		"id": "1hsyz7c",
		"subreddit": "sre",
		"score": 53,
		"comments": 11,
		"title": "SRE production readiness checklist",
		"url": "https://reddit.com/r/sre/comments/1hsyz7c/sre_production_readiness_checklist/",
		"theme": "prod safety"
	},
	{
		"id": "13d4i6v",
		"subreddit": "sre",
		"score": 50,
		"comments": 5,
		"title": "List of Post-Mortems",
		"url": "https://reddit.com/r/sre/comments/13d4i6v/list_of_postmortems/",
		"theme": "postmortem"
	},
	{
		"id": "11dsa6o",
		"subreddit": "sre",
		"score": 45,
		"comments": 14,
		"title": "When choosing SaaS vendors make sure you write this into your contracts.",
		"url": "https://reddit.com/r/sre/comments/11dsa6o/when_choosing_saas_vendors_make_sure_you_write/",
		"theme": "vendor trust"
	}
];

export const BUYER_QUOTES: BuyerQuote[] = [
	{
		"subreddit": "sre",
		"score": 66,
		"keyword": "on-call",
		"postTitle": "Became SRE. Highly regret it. Help.",
		"body": "I work in an environment where getting 50+ pages per week is common. I dread on-call weeks as a result. I have to put my entire life on hold because I am constantly anticipating the next alert.",
		"url": "https://reddit.com/r/sre/comments/113t8ou/became_sre_highly_regret_it_help/"
	},
	{
		"subreddit": "sre",
		"score": 63,
		"keyword": "3am page",
		"postTitle": "i once got paged on the subway and emerged in the midst of a SEV0 outage",
		"body": "it was a sunday. had to steal wifi from an urban outfitters on 5th ave to manage it. what's your most inconveniently timed page?",
		"url": "https://reddit.com/r/sre/comments/1e0t000/i_once_got_paged_on_the_subway_underground_and/"
	},
	{
		"subreddit": "devops",
		"score": 340,
		"keyword": "rollback",
		"postTitle": "The next time your devs complain about production being locked down",
		"body": "While building a feature, we performed a database migration command locally, but it incorrectly pointed at production — one of your worst nightmares.",
		"url": "https://reddit.com/r/devops/comments/1axfxob/the_next_time_your_devs_complain_about_production/"
	},
	{
		"subreddit": "sre",
		"score": 16,
		"keyword": "outage",
		"postTitle": "Have you ever caused a major outage?",
		"body": "You can't call yourself an engineer if you haven't taken down prod at least once.",
		"url": "https://reddit.com/r/sre/comments/1foghyl/have_you_ever_caused_a_major_outage/"
	},
	{
		"subreddit": "devops",
		"score": 324,
		"keyword": "toil",
		"postTitle": "Why is DevOps still such a fragmented, exhausting mess in 2025?",
		"body": "DevOps was supposed to make life easier for developers, but honestly, it still feels like an endless headache. Every problem needs a different tool.",
		"url": "https://reddit.com/r/devops/comments/1i538r1/why_is_devops_still_such_a_fragmented_exhausting/"
	},
	{
		"subreddit": "sre",
		"score": 45,
		"keyword": "vendor trust",
		"postTitle": "When choosing SaaS vendors make sure you write this into your contracts",
		"body": "Just came off a super frustrating experience with a SaaS 'observability' vendor where essentially they provide the ability for us to back up our log data locally in an S3 bucket that...",
		"url": "https://reddit.com/r/sre/comments/11dsa6o/when_choosing_saas_vendors_make_sure_you_write/"
	},
	{
		"subreddit": "devops",
		"score": 349,
		"keyword": "production fires",
		"postTitle": "I'll fix your cloud/SRE problem in 48 hours and for free",
		"body": "3 years of experience stabilizing cloud chaos, scaling infrastructure, optimizing observability, and putting out production fires nobody else could trace.",
		"url": "https://reddit.com/r/devops/comments/1kk685o/im_done_applying_ill_fix_your_cloudsre_problem_in/"
	},
	{
		"subreddit": "sre",
		"score": 62,
		"keyword": "postmortem",
		"postTitle": "seeing my name in the postmortem",
		"body": "seeing my name in the postmortem",
		"url": "https://reddit.com/r/sre/comments/1fz23bq/seeing_my_name_in_the_postmortem/"
	}
];
